### ISSUE TITLE
grails 3 plugin release

### ISSUE THREAD

**Issue by edavism** [budjb/grails-rabbitmq-native#70]
Hi,
   is there a grails 3 compatible version planning to be released soon?

thanks,
Emilio

**Comment by budjb** [comment]
I'm actively working on finishing up the grails 2.x -> 3.x migration.  Hoping to have this released in a week or two.

**Comment by edavism** [comment]
Great!

**Comment by budjb** [comment]
I have released a beta of the grails 3 plugin.  It has feature parity with the grails 2 plugin.  You can find it here: https://bintray.com/budjb/grails-plugins/rabbitmq-native.

I'd love feedback on whether this works correctly or not.

**Comment by robertoschwald** [comment]
The documentation seem to be still for Grails 2 in parts. E.g. it states:
"Configuration of the connection to the RabbitMQ server is done in your project's grails-app/conf/Config.groovy file."
Must be application.yml or application.groovy. But I still receive a MissingConfigurationException if I place the config in application.groovy.

**Comment by robertoschwald** [comment]
Grails 3 documentation is available on http://budjb.github.io/grails-rabbitmq-native/3.x/latest/ now. Thanks for updating the readme.

**Comment by budjb** [comment]
Closing this since Grails 3 support has been out for a while.
